---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/init}
inputs:
- name: davcli-src
  path: src/github.com/cloudfoundry/bosh-davcli
run:
  path: src/github.com/cloudfoundry/bosh-davcli/ci/tasks/run-unit.sh
