---
groups:
  - name: davcli
    jobs:
      - test
      - promote

jobs:
  - name: test
    serial: true
    plan:
      - {trigger: true, get: davcli-src, resource: davcli-in}

      - task: test
        file: davcli-src/ci/tasks/run-test.yml

  - name: promote
    plan:
      - aggregate:
        - get: davcli-src
          resource: davcli-in
          trigger: true
          passed:
            - test

        - put: version-semver
          params:
            bump: patch

      - aggregate:
        - do:
          - task: build-linux
            file: davcli-src/ci/tasks/build.yml
            params:
              GOOS: linux
          - put: release-bucket-linux
            params: {file: out/davcli-*-linux-amd64}

        - do:
          - task: build-windows
            file: davcli-src/ci/tasks/build.yml
            params:
              GOOS: windows
          - put: release-bucket-windows
            params: {file: out/davcli-*-windows-amd64}

resources:
  - name: davcli-in
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-davcli
      branch: master

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      bucket: {{davcli_release_bucket}}
      access_key_id: {{davcli_release_bucket_access_key}}
      secret_access_key: {{davcli_release_bucket_secret_key}}

  - name: release-bucket-linux
    type: s3
    source:
      regexp: davcli-(.*)-linux-amd64
      bucket: {{davcli_release_bucket}}
      access_key_id: {{davcli_release_bucket_access_key}}
      secret_access_key: {{davcli_release_bucket_secret_key}}

  - name: release-bucket-windows
    type: s3
    source:
      regexp: davcli-(.*)-windows-amd64
      bucket: {{davcli_release_bucket}}
      access_key_id: {{davcli_release_bucket_access_key}}
      secret_access_key: {{davcli_release_bucket_secret_key}}
